# Generated by web-ci-dev-base v0.1.0. Do not edit directly.
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $repoRoot '.web-ci-base.json'
$resultDirRelative = '.ai-results'
$resultDir = Join-Path $repoRoot $resultDirRelative
$timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
$reportPath = Join-Path $resultDir "local-tests-$timestamp.txt"
$originalLocation = Get-Location

function Require-Command {
    param([Parameter(Mandatory = $true)][string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "Required command not found: $Name"
    }
}

function Get-NormalizedStatus {
    param([Parameter(Mandatory = $true)][string]$IgnoredRelativeDir)
    $prefix = $IgnoredRelativeDir.TrimEnd('/', '\')
    $pattern = [regex]::Escape($prefix) + '([/\\]|$)'
    $lines = @(& git status --porcelain=v1 --untracked-files=all 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw 'git status failed'
    }
    return @($lines | Where-Object {
        $payload = if ($_.Length -gt 3) { $_.Substring(3) } else { $_ }
        $payload -notmatch $pattern
    } | ForEach-Object { [string]$_ })
}

function Write-ReportLine {
    param([string]$Value = '')
    $Value | Out-File -FilePath $reportPath -Encoding utf8 -Append
}

try {
    Require-Command -Name 'git'
    if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
        throw "Missing config: $configPath"
    }

    $config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
    $testProgram = [string]$config.adapter.test_program
    $testArgs = @($config.adapter.test_args | ForEach-Object { [string]$_ })
    Require-Command -Name $testProgram

    New-Item -ItemType Directory -Force -Path $resultDir | Out-Null
    Set-Location $repoRoot

    $branch = (& git branch --show-current).Trim()
    if ($LASTEXITCODE -ne 0) { throw 'git branch failed' }
    $commit = (& git rev-parse HEAD).Trim()
    if ($LASTEXITCODE -ne 0) { throw 'git rev-parse failed' }
    $before = @(Get-NormalizedStatus -IgnoredRelativeDir $resultDirRelative)

    @(
        "timestamp=$timestamp"
        "repo=$repoRoot"
        "branch=$branch"
        "commit=$commit"
        "test_program=$testProgram"
        "test_args=$($testArgs -join ' ')"
        '===== git status before ====='
    ) | Set-Content -LiteralPath $reportPath -Encoding utf8
    foreach ($line in $before) { Write-ReportLine $line }

    Write-ReportLine
    Write-ReportLine '===== test output ====='
    $output = @(& $testProgram @testArgs 2>&1)
    $testExit = $LASTEXITCODE
    foreach ($line in $output) {
        Write-Host $line
        Write-ReportLine ([string]$line)
    }

    $after = @(Get-NormalizedStatus -IgnoredRelativeDir $resultDirRelative)
    Write-ReportLine
    Write-ReportLine '===== git status after ====='
    foreach ($line in $after) { Write-ReportLine $line }

    $beforeText = $before -join "`n"
    $afterText = $after -join "`n"
    if ($beforeText -ne $afterText) {
        Write-ReportLine 'worktree_changed=true'
        Write-Host "Report: $reportPath"
        if ($testExit -ne 0) { exit $testExit }
        exit 97
    }

    Write-ReportLine 'worktree_changed=false'
    Write-ReportLine "test_exit=$testExit"
    Write-Host "Report: $reportPath"
    exit $testExit
}
catch {
    if (Test-Path -LiteralPath $resultDir) {
        try { Write-ReportLine "ERROR: $($_.Exception.Message)" } catch { }
    }
    Write-Error $_
    exit 1
}
finally {
    Set-Location $originalLocation
}
